"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { useToast } from "@/components/ToastProvider";
import { formatRupiah, formatDate } from "@/lib/utils";
import StatusBadge from "@/components/StatusBadge";
import EmptyState from "@/components/EmptyState";
import Button from "@/components/Button";

const STATUSES = ["PENDING", "PROCESSING", "COMPLETED", "FAILED", "CANCELLED", "REFUNDED"] as const;
type Order = { id: string; order_number: string; total_amount: number; status: string; created_at: string; profiles: { full_name: string | null; email: string } | null };

export default function AdminOrdersPage() {
  const supabase = createClient(); const toast = useToast();
  const [orders, setOrders] = useState<Order[]>([]); const [loading, setLoading] = useState(true); const [acting, setActing] = useState<string | null>(null); const [notes, setNotes] = useState<Record<string,string>>({});
  async function load() { setLoading(true); const { data, error } = await supabase.from("orders").select("id, order_number, total_amount, status, created_at, profiles(full_name, email)").order("created_at", { ascending: false }).limit(100); if (error) toast.show(error.message, "error"); setOrders((data as Order[]) || []); setLoading(false); }
  useEffect(()=>{load(); /* eslint-disable-next-line react-hooks/exhaustive-deps */},[]);
  async function updateStatus(id:string,status:string) { setActing(id); try { const res=await fetch(`/api/admin/orders/${id}/status`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,note:notes[id]||undefined})}); const json=await res.json(); if(!res.ok){toast.show(json.message||"Gagal mengubah status.","error");return;} toast.show(json.message,"success"); await load(); } catch { toast.show("Koneksi bermasalah.","error"); } finally {setActing(null);} }
  return <div className="animate-page-in"><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-600">Operasional</p><h1 className="mt-1 text-2xl font-black text-slate-900">Kelola Pesanan</h1><p className="mt-1 text-sm text-slate-500">Tandai pesanan selesai, gagal, dibatalkan, atau refund bila diperlukan.</p></div><button onClick={load} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold shadow-sm">↻ Refresh</button></div>{loading?<div className="animate-pulse rounded-2xl bg-white p-6 text-sm text-slate-500">Memuat pesanan...</div>:orders.length===0?<EmptyState title="Belum ada order"/>:<div className="space-y-3">{orders.map(o=><div key={o.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-black text-slate-900">{o.order_number}</p><p className="text-xs text-slate-500">{o.profiles?.full_name||o.profiles?.email||"Pengguna"} · {formatDate(o.created_at)}</p></div><div className="flex items-center gap-3"><b className="text-blue-600">{formatRupiah(o.total_amount)}</b><StatusBadge status={o.status}/></div></div><div className="mt-4 grid gap-2 md:grid-cols-[1fr_auto]"><input value={notes[o.id]||""} onChange={e=>setNotes(v=>({...v,[o.id]:e.target.value}))} placeholder="Catatan admin (opsional)" className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none focus:border-blue-500"/><select value={o.status} disabled={acting===o.id} onChange={e=>updateStatus(o.id,e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-bold outline-none focus:border-blue-500">{STATUSES.map(s=><option key={s} value={s}>{s}</option>)}</select></div>{o.status!=="REFUNDED"&&<div className="mt-2 flex flex-wrap gap-2"><Button onClick={()=>updateStatus(o.id,"COMPLETED")} loading={acting===o.id}>✓ Tandai Selesai</Button>{o.status!=="FAILED"&&<button onClick={()=>updateStatus(o.id,"FAILED")} className="rounded-xl border border-red-200 px-3 py-2 text-sm font-bold text-red-600">Gagal</button>}{o.status!=="CANCELLED"&&<button onClick={()=>updateStatus(o.id,"CANCELLED")} className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold text-slate-600">Batalkan</button>}{o.status!=="COMPLETED"&&<button onClick={()=>updateStatus(o.id,"REFUNDED")} className="rounded-xl border border-amber-200 px-3 py-2 text-sm font-bold text-amber-700">Refund</button>}</div>}</div>)}</div>}</div>;
}
